# Users with delete access can run this workflow to delete packages

name: DeletePackages

on: 
  workflow_dispatch:
      inputs:
        owner:
          description: 'Repo Owner'     
          required: true
          default: 'ballerina-platform'
        repo:
          description: 'Repository'     
          required: true
          default: 'ballerina-lang'
        packages:
          description: 'Comma separated list of packages (groupId.artifactId)'
          required: true
        version:
          description: 'Package version'
          required: true

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Read access list
        run: "cat ./delete-packages-scripts/usernames_with_package_delete_access.json | jq -r '.usernames[]|select(.username==\"${{github.actor}}\").username' > /tmp/auth-user.json"
      - name: Set authorized username
        id: setUname
        run: printf "::set-output name=foundUname::%s" $(cat /tmp/auth-user.json)
      - name: Read and delete packages
        if: steps.setUname.outputs.foundUname != ''
        run: |
          IFS=',' read -r -a package_array <<< "${{ github.event.inputs.packages }}"
          for package in "${package_array[@]}"; do
            package=$(echo $package | xargs)
            echo "Fetching versions of package: $package"
            version_ids=$(curl -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/${{ github.event.inputs.owner }}/packages/maven/$package/versions)
            version_id=$(echo $version_ids | jq -r '.[] | select(.name=="${{ github.event.inputs.version }}")|.id')
            if [[ -n $version_id ]]; then
              curl -X DELETE -H "Authorization: bearer ${{ secrets.DELETE_PACKAGE_PAT }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/${{ github.event.inputs.owner }}/packages/maven/$package/versions/$version_id
              echo "Deleted package version: $version_id"
            fi
          done
